### ISSUE TITLE
Add more detailed instructions under development section

### ISSUE THREAD

**Issue by RonanMacF** [gianarb/coc-grammarly#12]
Great project thanks for doing most of the ground work on it. I am looking to add to this project but am having some difficulty in getting it up and running, following your instructions it seems that all I need to do is clone the repo and run `npm run build`, however, this spits out errors for me. I have tried importing the modules manually with `npm install inversify` etc but no joy could you add some further instructions on how I could get up and running. Thanks
```

> @ build /Users/ronan/grammarly
> run-s -l build:*

[build:packages ] 
[build:packages ] > @ build:packages /Users/ronan/grammarly
[build:packages ] > rollup -c
[build:packages ] 
[build:packages ] 
[build:packages ] ./packages/grammarly-api/src/index.ts → ./packages/grammarly-api/dist/index.d.ts...
[build:packages ] created ./packages/grammarly-api/dist/index.d.ts in 2.7s
[build:packages ] 
[build:packages ] ./packages/grammarly-language-server/src/index.ts → ./packages/grammarly-language-server/dist/index.d.ts...
[build:packages ] packages/grammarly-language-server/src/index.ts(2,27): error TS2307: Cannot find module 'inversify' or its corresponding type declarations.
[build:packages ] packages/grammarly-language-server/src/index.ts(23,22): error TS2554: Expected 2-3 arguments, but got 1.
[build:packages ] 
[build:packages ] [!] (plugin dts) Error: Could not load /Users/ronan/grammarly/packages/grammarly-language-server/src/index.ts: Failed to compile. Check the logs above.
[build:packages ] Error: Could not load /Users/ronan/grammarly/packages/grammarly-language-server/src/index.ts: Failed to compile. Check the logs above.
[build:packages ]     at error (/Users/ronan/grammarly/node_modules/rollup/dist/shared/rollup.js:5275:30)
[build:packages ]     at throwPluginError (/Users/ronan/grammarly/node_modules/rollup/dist/shared/rollup.js:18232:12)
[build:packages ]     at Object.error (/Users/ronan/grammarly/node_modules/rollup/dist/shared/rollup.js:18839:24)
[build:packages ]     at Object.load (/Users/ronan/grammarly/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1397:26)
[build:packages ]     at /Users/ronan/grammarly/node_modules/rollup/dist/shared/rollup.js:19041:25
[build:packages ] 
[build:packages ] npm ERR! code ELIFECYCLE
[build:packages ] npm ERR! errno 1
[build:packages ] npm ERR! @ build:packages: `rollup -c`
[build:packages ] npm ERR! Exit status 1
[build:packages ] npm ERR! 
[build:packages ] npm ERR! Failed at the @ build:packages script.
[build:packages ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[build:packages ] 
[build:packages ] npm ERR! A complete log of this run can be found in:
[build:packages ] npm ERR!     /Users/ronan/.npm/_logs/2021-02-14T13_10_12_743Z-debug.log
ERROR: "build:packages" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `run-s -l build:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ronan/.npm/_logs/2021-02-14T13_10_12_785Z-debug.log
```

**Comment by marcoaaguiar** [comment]
Hi, Ronan! What node version are you using?
There have been some reports of incompatibility with node 15.

**Comment by gianarb** [comment]
```
$ node -v
v15.11.0
```

```
$ npm -v
7.6.3
```

This is what I do:
```
$ npm run build
```

And it works fine for me. At least the build process! I am closing this for now. Will reopen if you can provide more details! Thanks
